<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 1" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="C:/Users/Bowen/Desktop/coding/cpt200/whats_in_my_fridge/scrape_testing/cleaner.py" status="error" test="cleaner" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\Bowen\.p2\pool\plugins\org.python.pydev_5.6.0.201703221358\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users\Bowen\Desktop\coding\cpt200\whats_in_my_fridge\scrape_testing\cleaner.py", line 9, in <module>
    with open ('recipe_link_file.txt') as link_file:
FileNotFoundError: [Errno 2] No such file or directory: 'recipe_link_file.txt'
ERROR: Module: cleaner could not be imported (file: C:/Users/Bowen/Desktop/coding/cpt200/whats_in_my_fridge/scrape_testing/cleaner.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="whats_in_my_fridge scrape_testing"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
